kind = "web"
previewPath = "/"
title = "Mapa Interativo RPG"
version = "1.0.0"
id = "artifacts/mapa-rpg"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19964

[services.development]
run = "pnpm --filter @workspace/mapa-rpg run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mapa-rpg", "run", "build" ]
publicDir = "artifacts/mapa-rpg/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19964"
BASE_PATH = "/"
